apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerConfig
metadata:
  name: server
  namespace: gloo-mesh
spec:
  destinationServers:
  - port:
      name: grpc
    ref:
      cluster: gloo-gateway
      namespace: gloo-mesh
      name: rate-limiter
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 10
        unit: MINUTE
      value: counter
---

apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: client
  namespace: gloo-mesh
spec:
  raw:
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter


---

apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerSettings
metadata:
  name: settings
  namespace: gloo-mesh
spec:
  destinationServer:
    port:
      name: grpc
    ref:
      cluster: gloo-gateway
      name: rate-limiter
      namespace: gloo-mesh